### ISSUE TITLE
.gitmodules should probably be checked in

### ISSUE THREAD

**Issue by justinas** [vilniusgolang/website#1]
As of now, `git submodule update` errors out:

    No submodule mapping found in .gitmodules for path 'themes/vienna'

I'm not experienced with git submodules, but it seems like .gitmodules is missing altogether from the repo.

**Comment by ernestas-poskus** [comment]
sorry missed this one, add vienna theme as submodule and rebased 
when website.git repo is cloned `git submodule update` should do the job

**Comment by justinas** [comment]
Works wonderfully now with `pull; submodule init; submodule update`. :+1:
