### ISSUE TITLE
Go Community

### ISSUE THREAD

**Issue by ernestas-poskus** [vilniusgolang/website#2]
@vilniusgolang/gophers 

Hey the website is live http://vilniusgolang.github.io/ code & design contributions are welcome, I have a few questions:

0. Do we need http://www.vilniusgolang.lt domain ?

1. Should I merge 'Schedule Tools Presentations' top navigation menu with middle one (replace text with icons) - make it consistent ? 

2. When do we plan first meeting ? we had short discussion with @remigijusj that proper time is after summer ? What do you think ?

3. Other suggestions ? What to add ? Remove ? Change ?

P.S. Contribute or write about golang #! shebang scripts or command line tools / goodies here http://vilniusgolang.github.io/tools/

**Comment by mmozuras** [comment]
1. yes.
2. yes.
3. September sounds good.
4. Feel free to ask our designers for help. And https://developers.google.com/speed/pagespeed/insights/?url=http%3A%2F%2Fvilniusgolang.github.io%2F

**Comment by remigijusj** [comment]
Hi,

1. would be nice
3. middle of September, some day in a middle of a week. About the place -
perhaps Wix would be willing to host?
4. if we can have designer's help, it would be awesome

**Comment by ernestas-poskus** [comment]
:ok_hand: 

1. Will order in a few days
2. done & optimised (will do asset concatenation & minification later)
3. September it is. I bet we could find a shelter in Wix or Vinted  
4. Will ask Vinted designers to give a hand on visuals

**Comment by ernestas-poskus** [comment]
cc @doneland can you schedule September in meetup.com ?

**Comment by ernestas-poskus** [comment]
I have contacted Edgaras (sole manager of Golang group meetup.com) personally, he is overwhelmed with work but is willing to engage with community. Edgaras has made be co-organiser in meetup.com so now I can schedule meeting date.
