### ISSUE TITLE
First VilniusGolang meetup

### ISSUE THREAD

**Issue by ernestas-poskus** [vilniusgolang/website#3]
Good news everyone @vilniusgolang/gophers 

A little later but still in September I have came up with a date & place for a event.

Vinted has agreed to host & sponsor our first meeting. 

Event will happen in 2015-09-24 / 19:00 @ VintedHQ at Žirmūnų g. 70, Vilnius 09133

We already have a speaker:
 - @tasdomas who suggested to tell about juju https://github.com/juju/juju [please confirm]
 - I am deciding topic between: reflection, concurrency or introduction to Go 

**Speakers are more than welcome !**

For speakers:
 - Golang related topic, experience, findings & else
 - English language
 - slides / short video
 - 10 to 15min presentations

Meetup.com -  will create meetup info.

Hope to meet all of you there :hand:

**Comment by mmozuras** [comment]
> 10 to 15min presentations

That seems rather short. Reasons? :smile:

**Comment by ernestas-poskus** [comment]
This is rather guidance than limit.

**Comment by tasdomas** [comment]
Hey guys,
I'm very sorry - I have a prior commitment on Sep 24th, won't be able to
attend and talk about juju.

Domas

**Comment by ernestas-poskus** [comment]
hey @tasdomas 

That's pity but I am willing to reschedule the event in order to accommodate your schedule. 
For event to happen fluently I want to have a guarantee of at least 2 speakers. 
Please share your schedule & availability.

**Comment by justinas** [comment]
I am willing to talk about Go build modes that were introduced in 1.5.

**Comment by ernestas-poskus** [comment]
@justinas excellent !! :+1:

**Comment by justinas** [comment]
Is there a final consensus on whether we're postponing yet? When we decide, we should put up the event on [usergroups.lt](http://usergroups.lt) IMO.

**Comment by tasdomas** [comment]
Hi,
I could probably make it one week later - Oct 1st, but I don't want to
derail the first meetup just because I'm busy.

Domas

**Comment by ernestas-poskus** [comment]
Lets shift 1 week or more if needed. Oct 1 is fine for me.

@tasdomas can you make it ? how about you @justinas ?

Oct 4 - 7 is good as well.

**Comment by justinas** [comment]
@ernestas-poskus Oct 1, 4, 7 are all okay with me. 4 is Sunday, so some people might be out of town: most meetups happen on weekdays.

**Comment by ernestas-poskus** [comment]
Typo I meant 5-8 :smile:

**Comment by tasdomas** [comment]
@ernestas-poskus, Oct 1, 5-8 work for me.


Domas

**Comment by ernestas-poskus** [comment]
@tasdomas @justinas 

So it is official we will meet on 2015-10-06 in 19:00 @ VintedHQ at Žirmūnų g. 70, Vilnius 09133

Will add event to meetup.com tomorrow morning

**Comment by ernestas-poskus** [comment]
http://www.meetup.com/Vilnius-Golang/events/225531544/

**Comment by justinas** [comment]
Shall I suggest a better description for my talk? Cross-compilation is not the same as build modes: I'm specifically talking about the feature that was introduced in Go 1.5. 

>Bringing Go to C and other languages: building and using shared and static libraries.

**Comment by ernestas-poskus** [comment]
@justinas updated
