### ISSUE TITLE
Go 1.6 release party

### ISSUE THREAD

**Issue by justinas** [vilniusgolang/website#4]
Hi gophers,

Go 1.6 is expected to ship sometime in February and the community [is calling to organize release parties](https://github.com/golang/go/wiki/Go-1.6-release-party) on the 17th of February.

What are your thoughts on hosting an event (either giving talks or anything else) on that date?

**Comment by ernestas-poskus** [comment]
I am overwhelmed with wedding stuff and from the middle of February I won't be in Lithuania. Would you like to organize it ?

**Comment by justinas** [comment]
Sure. I'll do an interest check for now and see if I could get an auditorium in my faculty for the meetup.

**Comment by ernestas-poskus** [comment]
:+1:

**Comment by l3pp4rd** [comment]
+1 in case, we can provide a conference room in Kaunas, otherwise - see you in Vilnius ;)

**Comment by justinas** [comment]
So I'm still figuring out the details about the venue, but in the mean time, would anyone like to give a talk at the event? Anything works, as short as 5 minutes: could be a tutorial, a story of how you fell in love with go, or simply a presentation of your cool Github project.

I myself am planning to present the changes in Go 1.6, as per the theme of the event :wink:

**Comment by l3pp4rd** [comment]
Hi @justinas I always can present some [go](https://github.com/DATA-DOG?utf8=%E2%9C%93&query=go) would not be a problem if there aren't many speakers :) @rndz would you join?

**Comment by justinas** [comment]
@l3pp4rd great! Do you have the title for your talk yet?

**Comment by l3pp4rd** [comment]
I'll come back with it tomorrow ;)

**Comment by l3pp4rd** [comment]
OK, I'll speak about BDD tests, the [title and description](http://gophers.lt/post/go16-release-party-meetup/) do you know where the event will be hosted? probably we need to somehow merge the community, can talk about it during the event, I would prefer if we all have a common website as golang lithuania user group and it does not really matter where the events are hosted Vilnius, Kaunas or another city. Simply all gophers who wish to take action in community, could have access granted and be able to post an event. Anyway, something to discuss during the event.

**Comment by justinas** [comment]
I am still figuring out the details about the location. Sorry if that causes trouble, I will try to come back with the final info ASAP.

As for a merger, you should probably discuss this with @ernestas-poskus. If I'm not mistaken, he's the original creator of @vilniusgolang.

**Comment by ernestas-poskus** [comment]
Guys sorry for delay.

>  I'll speak about BDD tests, the title and description

same should be added to vilniusgolang.lt and on meetup.com. I will give you both write rights to https://github.com/vilniusgolang/website and https://github.com/vilniusgolang/website and https://github.com/vilniusgolang/vilniusgolang.github.io

> merge the community

definitely  

> I am still figuring out the details about the location. Sorry if that causes trouble, I will try to come back with the final info ASAP.

Normally I would suggest Vinted HQ but due to my absence I don't know if someone will replace me, I can ask out if you are out of options.

**Comment by l3pp4rd** [comment]
@ernestas-poskus I'll open another issue to discuss the community join.

@justinas on 17-th we have kaunasphp conference at our headquarters, any other day would be suitable :) otherwise if you have troubles looking up for location, I could ask vilniusphp community, they probably could help with a conf room at Galvydzio g. 5 vilniuje. I'll be out of the country for few days from Wednesday, so it would be good to resolve this tomorrow.

**Comment by justinas** [comment]
(posted on the wrong issue before)

Some news on the venue (finally!): we'll be gathering at VU MIF, Naugarduko st. 24. The date is February 17th and I propose starting at 18:30.

I'm preparing the post for vilniusgolang.lt. @ernestas-poskus could I get the permissions to post on meetup.com?

**Comment by ernestas-poskus** [comment]
@justinas please most the text here I will post it, I am not the owner of meetup.com only co-organizer.

**Comment by justinas** [comment]
@ernestas-poskus created a pull request with the announcement. (#6)

**Comment by justinas** [comment]
Warning: there is no public wi-fi at the location, so please have your presentation available locally. @l3pp4rd

**Comment by l3pp4rd** [comment]
@justinas I'll try to be around 18:30, but if I'll be a little late be the first speaker ;)
